# Generated by Django 2.2.9 on 2020-04-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200426_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='photo',
        ),
    ]
